Revamped architecture copied back from defect detector (ckt-defect)

diff --git a/src/program b/src/program
--- a/src/program
+++ b/src/program
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+firmware=bin/snd-player-0.3.0.bin
+
 if [ $# -eq 0 ]
   then
     port=/dev/ttyACM0
@@ -9,6 +11,26 @@ fi
 
 while true
 do
+	success=1
+
+	echo
+
+	echo -n "Waiting for port"
+	touch $port > /dev/null 2> /dev/null
+	while [ $? -ne 0 ]
+	do
+		echo -n .
+		sleep 1
+		touch $port > /dev/null 2> /dev/null
+	done
+	
+	echo
+
+	echo "Performing 1200bps touch reset..."
+	stty -F /dev/ttyACM0 1200
+#	python3 -c "import serial; import time; ser = serial.Serial(\"/dev/ttyACM0\", 1200, timeout=1); time.sleep(1); ser.close()"
+
+	echo -n "Waiting for port"
 	touch $port > /dev/null 2> /dev/null
 	while [ $? -ne 0 ]
 	do
@@ -17,14 +39,44 @@ do
 		touch $port > /dev/null 2> /dev/null
 	done
 
+	echo
+
 	echo -e "\n\033[1;33mProgramming\033[0m\n"
 	espeak "Programming"
 
-	make firmware BIN=build-0.2.0 PORT=$port
+	echo Programming Try \#1...
+	esptool --chip esp32s2 --port $port write-flash 0x0 $firmware
 
-	echo -e "\033[0;32mComplete\033[0m\n"
-	espeak "Complete"
+	if [ $? -ne 0 ]
+	then
+	        echo Programming Try \#2...
+	        echo Wait...
+	        sleep 1
+		esptool --chip esp32s2 --port $port write-flash 0x0 $firmware
+		if [ $? -ne 0 ]
+		then
+			success=0
+		fi
+	fi
 
-	sleep 1
-	make terminal PORT=$port
+	if (( $success == 1 ))
+	then
+		echo
+		echo -e "\033[0;32mComplete\033[0m\n"
+		espeak "Complete"
+	else
+		echo
+		echo -e "\033[0;31mFailed\033[0m\n"
+		espeak "Failed"
+	fi
+
+	sleep 2
+
+	touch $port > /dev/null 2> /dev/null
+	while [ $? -eq 0 ]
+	do
+		echo -n +
+		sleep 1
+		touch $port > /dev/null 2> /dev/null
+	done
 done
